Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -28,6 +28,14 @@ jobs:
       - name: Set environment variables
         run: echo "UPDATGAME=${{ secrets.UPDATGAME }}"
 
-      - name: Build with Gradle
-        run: ./gradlew build
+      - name: Find and execute gradlew
+        run: |
+               GRADLEW_PATH=$(find . -name "gradlew" | head -n 1)
+                if [ -z "$GRADLEW_PATH" ]; then
+                  echo "gradlew not found"
+                        exit 1
+                      else
+                        chmod +x $GRADLEW_PATH
+                           $GRADLEW_PATH build
+                                    fi
 
